version: "3"

services:
  app:
    build: ./application
    tty: true
    image: golang
    ports:
      - 8080:8080
    container_name: todo-test-container
    volumes:
      - ./:/go/src/api

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: tomoaki7
      MYSQL_PORT: 3306
    ports:
      - 3300:3306
